---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.14.5
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: pihole
    env:
      - name: &name EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: &secret external-dns-pihole
            key: *name
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    extraArgs:
      - --pihole-server=https://pihole.itstoni.com
      - --ignore-ingress-tls-spec
      - --ingress-class=internal
    policy: upsert-only
    sources: ["crd", "ingress"]
    domainFilters: ["${SECRET_DOMAIN}"]
    registry: noop
    serviceMonitor:
      enabled: true
