---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-pihole
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        EXTERNAL_DNS_PIHOLE_PASSWORD: "{{ .pihole_password }}"
  refreshInterval: 15m
  data:
    - secretKey: pihole_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 92f5c243-26a1-48fb-b845-b1bb0119e705
        property: password
