# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: redis-secrets
type: Opaque
stringData:
    redis_password: ENC[AES256_GCM,data:iK/dy0eQPqKw4Y26,iv:hnrJYWQ/n4VdTJGULyxxu1t15ZvOCni1spanb71ztkg=,tag:AMvFkh7cPX8Yyu/js/pLJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVmxYeGgrT05jei9ubG5s
            cUllRGp5MU4rQmc2SFA1bEppYVdqRTlxSlRFCnV4eUdydE8zTW4weUtqVFlFRGNm
            ZzdoWWdGa0QwWkJHOE5DV3hnSmxtSmMKLS0tIDNYcTdrcHh0emh4TVNpUFYwRmVu
            R1hXOUVRd0hGVVprNXdMckowcnRQMDgKPJoqk9JetF9590p1C4iIRFKSayKhepGg
            O7g8r47ib1EnTGY7fLhkB0JvGofoBA2Qorv3/TXwpLAM1dYFPjcnTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-08T17:05:35Z"
    mac: ENC[AES256_GCM,data:M8Gor0hlvQOGhPHpcKZZsVAhSiwgcjB76632oVCLZxuhCGQwIUxsOTgha5t71faBge0zxgg5geDeMRxAAuyYh38lY83OT04AWJdRj1Z5O/+T4KAC6f2tg/vcxy8FSvZFzT17qrOD97f3UGkB5Or7cSOxLHgYRmpxBqqmdiaiyKc=,iv:t4G1zd9p2+zs+aF57ZHbAcvbPeGJSy1YiNw3rieFSdc=,tag:ahr4Nd9w+aX/FyN92bbjqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
