---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-secrets
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CF_TUNNEL_ID: |-
          {{ .cf_tunnel_id }}
        CF_TUNNEL_SECRET: |-
          {{ .cf_tunnel_secret }}
        CF_TUNNEL_TOKEN: |-
          {{ .cf_tunnel_token }}
  refreshInterval: 15m
  data:
    - secretKey: cf_tunnel_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ${TUNNEL_SECRETS}
        property: id
    - secretKey: cf_tunnel_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ${TUNNEL_SECRETS}
        property: secret
    - secretKey: cf_tunnel_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ${TUNNEL_SECRETS}
        property: token
