---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - stable-secrets.sops.yaml
  - stable.yaml
  - staging-secrets.sops.yaml
  - staging.yaml
