---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: db
  labels:
    app.kubernetes.io/name: postgres-db
spec:
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql versioning=redhat
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2-10
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: openebs-hostpath
    resizeInUseVolumes: false
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-super-user
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
