apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:6yIIyunlWROijkgf7mufrTy0zKXqn9gn2vMUzSeLEKpsRVHj,iv:zmfUoHjbxkYUeW74bltU7V9vAzmiDJ6X/Vlj6mJJoA8=,tag:5estgSOjX5+7fF8gtr5XWQ==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:7TzlHFG+zS4XNGMCs3quvJaJPvQe8h/sT9qtdyXwGXlCRtB/63+UKruQMNrEvNFMu+IuHlXgDvi8BHKdmIjyMg7Umfbk9sS65pEWhcSWmvcuTOrvVzwEF51f4iDRnunih/iLiGHm3moM3iCXAa+ecFV7thU3Kchf4/Q4THDNNuuPMLNdzgyCp4qwNT34DUMelFnOY+i1VDmLXLkij9im7XM1NUdJk8meiC3djB8ys/Zud/ep44avUQ==,iv:FggcNj37bbR9ex8ZoPzp0s7vqJr2fnlv7/pf0eLRMuE=,tag:qOSTgUCcv3Fu/s/D6owjSA==,type:str]
    credentials.json: ENC[AES256_GCM,data:2hBZUHPXvDaR/TmWKuQ4vDvhg/WQIu1LTez5zvl020yu1eFmWK52DeK0gmP7HAEgIARqbSFSi9kLfBAJimhn3I7rjFKLABV/MPp1g2N54knp40FTvl64/T5P1f39wWvKyP5Q,iv:qUtCoXho29W0E61kiAFqdU2TdKLhu+Xk2UoUC9aLRNA=,tag:QU0h5nsdhNoineQm+nixug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcnpJbUVRZGNtTDdqVW9U
            eHRIZjRJcHlMa1NHYTVnZ2FIa1JJM1czNUZVClNnNlZEUjBuQllvbTh4U0dya1VY
            RSt2MmxZZzFBNjZKU1p2UTQzVHQyc28KLS0tIFhsU00wRktXYnRwaHRVaklhVHBh
            a045WEd3ZUE1cTdwT3dWTEszZk5FVEkKMVDBZ4X6jMSWFptM5rJJpWlxfdMjJCos
            Mlv/5qYWpgN64pm4k+434+zcHqYUV/0cQ8gL8OE24IkN1hCal3J0Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-04T04:40:14Z"
    mac: ENC[AES256_GCM,data:XVIPsGq7gMKIa1J3G1NtPlol45uMsGG6QFtTrVQpbcJYZ18EefeRg+QCi/il8sP2ya13ewTd6clSy9SlljZ3CQvSZt92kaHRHaQooc9SwMw2K/VvP3LG7dffVnrhim0hgefkfusKIN8BSjvVx7a3omsaXeI/WRGk2k2YmH/UCYE=,iv:Bl7fKUQJCB53n7p3sP4jyw3yD++Cagh8jgVd7TUFsxo=,tag:qZRv+Mq32E0nlJLG8vx72w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
