---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_TLD/./-}-production"
spec:
  secretName: "${SECRET_TLD/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_TLD}"
  dnsNames:
    - "${SECRET_TLD}"
    - "*.${SECRET_TLD}"
