---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_TLD/./-}-staging"
spec:
  secretName: "${SECRET_TLD/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_TLD}"
  dnsNames:
    - "${SECRET_TLD}"
    - "*.${SECRET_TLD}"
    - "*.staging.${SECRET_TLD}"
