apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:zeo72uzRnXfawzI9pcifKbZLijpAQUCzQacWO3KoKFS5GW2IS93YGaVEiM89XMrsCMqYlnRticHJif3l3n8WOFC0LKU4ZiMnYm/Mkf2m1HGvcXk7J0/pWSaFTOVuhg==,iv:Z+u07xu9BxIhISD2YCyTVypHo/MhK6c7iR0PqfPqKZI=,tag:RisD4JzAmRBiQycHYU9f6A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:fZZqwDzAXa1nP9k=,iv:KgZxsNXCtqgnKWPK1ekqDEPAtLItKlH24voFKezJqaE=,tag:0J1nrCV/KqR9QxK2Qjdr6A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:eHrtw6jTOKu8C8VtvPg=,iv:b5OOFM/XLYzgb96ErAFhKh+D+BcqxMWdp/gCAibDEsA=,tag:hsIUrNti2JAuQK7t0swkfA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VMxnmu+JanWs4gWcFMN323GpQ11++xdNzASUVBCJbxuSODQF,iv:bDdCPXcUm5GlnXe8N/8fuYkKrCGAxcdo3Wndml7Q4yg=,tag:UD6TxWXQRecORAtPB2GbAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVDZQYTlzZ2U5czNUU1Fi
            cHVhM05YcWZhOGdraDFFU002TGtLVTF0N1RBCnkxRlNVNkZycUZmbkpHOW5XQnJC
            dFQxRkc0dWZaeFNESmEyK3g3QjVjbFkKLS0tIDNZaGlCQWd1RUIvc3RWeFZhcGRr
            bzRPWlJrNnhuYXJQK2t2WHNzWVRrdVkKaLWFjpnxacZEshnGhOZg/4hElSt4EUhC
            wQVsGes+HtgplrOYo1uOhjXxXantConuaMeSHzafpnm3XAKF3BQ63A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-05T07:12:12Z"
    mac: ENC[AES256_GCM,data:g7sTy1rfKXcn9Ty0N2fXU9NTFnCgv47B1J57vqz/XZYfg/SR/z7jNr55Ts/8xWIwy/Vq+qdE5Oz+ZJhnW8K/RG6DJdmaVxYlAv3x5Mk77/Sg/WO3a0XOBOmNPBhMf3sz6OS3PzN02M+NcNlzWKI7fZ2Lho933IxNIoLKISIkbdA=,iv:ezS3wxbqiGNzb+xMgPhl8EbePwVTPF7SAj0kiK2LFwo=,tag:SxFj6O+dF/EpSUp8C9eqYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
