apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:zeo72uzRnXfawzI9pcifKbZLijpAQUCzQacWO3KoKFS5GW2IS93YGaVEiM89XMrsCMqYlnRticHJif3l3n8WOFC0LKU4ZiMnYm/Mkf2m1HGvcXk7J0/pWSaFTOVuhg==,iv:Z+u07xu9BxIhISD2YCyTVypHo/MhK6c7iR0PqfPqKZI=,tag:RisD4JzAmRBiQycHYU9f6A==,type:str]
    SECRET_CERT: ENC[AES256_GCM,data:UqL78BclDm+YPA==,iv:QVr0gfO6jXNKYgMT91dZvko/rQ7dxqZAKKXgk5zD9e4=,tag:3krQk0zkODvbz7kj194GLQ==,type:str]
    SECRET_TLD: ENC[AES256_GCM,data:FTQ5GI6bXsxhZsI=,iv:XE+zHlr3Rrb+B4NlSK1fbQ61HQBuU3nCc/2Q1+3tcjE=,tag:PRWwWpma5wCO39yjDfz7gg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:fZZqwDzAXa1nP9k=,iv:KgZxsNXCtqgnKWPK1ekqDEPAtLItKlH24voFKezJqaE=,tag:0J1nrCV/KqR9QxK2Qjdr6A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:eHrtw6jTOKu8C8VtvPg=,iv:b5OOFM/XLYzgb96ErAFhKh+D+BcqxMWdp/gCAibDEsA=,tag:hsIUrNti2JAuQK7t0swkfA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VMxnmu+JanWs4gWcFMN323GpQ11++xdNzASUVBCJbxuSODQF,iv:bDdCPXcUm5GlnXe8N/8fuYkKrCGAxcdo3Wndml7Q4yg=,tag:UD6TxWXQRecORAtPB2GbAQ==,type:str]
    NFS_IP: ENC[AES256_GCM,data:jYgT5WTIWDST,iv:paH10sSJwDxwxKuBmrbU2DCpoFxvdhuBmN92KqZz8x8=,tag:1k2YciacQpryPT7i1/KFMA==,type:str]
    NFS_SERVER_PATH: ENC[AES256_GCM,data:sDYcndCg4qIG,iv:rVfY2LozyixMWwc3PLMOT2AEvF6h4vnhgz9oqd75IzE=,tag:DZuQS14QLB5lRy3EZC5fTQ==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:9M//2h7l,iv:nwq8uPGaUAD3aKKBxmFvOSrPOSAJ+H12bdqmMdIqhkA=,tag:76ynOc6b2wKQM4sJkFMw5A==,type:str]
    S3_HOST: ENC[AES256_GCM,data:5+8wWBYW2wPCpwBxASU=,iv:fXCz5LeuGXLpAl66ZqdOElbzwnQhZslZujCO93FMLbk=,tag:aBS1H3+dyBNYNVD1A/UOnQ==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:tAHBUA7umTizRKozhDbhjITyXYU=,iv:D6Rlfu6V0buMCyuVl/XW1k8yiRiH5Iy6ax4QZs4W1yM=,tag:Sf00knOLh0sSlnBfOEwoKQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:jJD85uww4WistosqUnV5E/33OVvrO2DVPXoLsG1ZnZTdozK1XYnCwA==,iv:uFQa5/49hVrUDJy8iXzLVvbBoxtAB0zaxyygBVLoTNY=,tag:AIrWllASH/bZRS6M/J3o2A==,type:str]
    S3_REGION: ENC[AES256_GCM,data:H7nncUEY/JaS,iv:D3uznqSdH62NooW823yGAZ7msWBvqHvgDdKG4y8hzQk=,tag:RIOg/ymKJK/jJPrFm5hYFg==,type:str]
    THANOS_BUCKET: ENC[AES256_GCM,data:Z455x8gF,iv:07v5DV5YOuDjQ22WTjOuotlp4g+hecFTs7U74SBBt7w=,tag:8DP0N7FkHtlnyU2ZtS+2DA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVDZQYTlzZ2U5czNUU1Fi
            cHVhM05YcWZhOGdraDFFU002TGtLVTF0N1RBCnkxRlNVNkZycUZmbkpHOW5XQnJC
            dFQxRkc0dWZaeFNESmEyK3g3QjVjbFkKLS0tIDNZaGlCQWd1RUIvc3RWeFZhcGRr
            bzRPWlJrNnhuYXJQK2t2WHNzWVRrdVkKaLWFjpnxacZEshnGhOZg/4hElSt4EUhC
            wQVsGes+HtgplrOYo1uOhjXxXantConuaMeSHzafpnm3XAKF3BQ63A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-06T04:58:40Z"
    mac: ENC[AES256_GCM,data:Y85kwg1Cx8k3IYrz0B/8hdw72yjowWpDRPXHXtBSOtgcCkp3/k2S4pO05JF8okckx09g97Ee86Gyo0q1CYQt5TndHhZ2zcCNhYASv6FzFhMlax/DerAJ7OEC973M3YDYa+EBlXF5mF9rsaTeYmlxqFWVBmVzZLQxuKMHaFSmOqc=,iv:3c6NkE3Utqw0f23+NaC81QHpTq684+C13g4Ly/nFLGQ=,tag:6oIYi0mHMivP/ouVmd8nZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
