apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:51jh6u5B2jAwaGKD+I6uR4H4myTDyJYKjHEiqx3KAfumW0DhpQrNFWnBc5vFrJWSEpFYlanG6B75JPgvZpg+rJhc1yS6wumx7rTTLtjz7AyNj2sujz0VE7OIGnRcZg==,iv:EVbVmmO7socxgnS26CrKsnCf3ZPe00n/bFywvHnDaTQ=,tag:ZWUAhYXT9TBo17H0+Y0wZw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:TRR5d3+TXMGruys=,iv:3zQHYWkejg09NJ5DdfYmQoT+UUV7+pJ+ei/dwGLxJEY=,tag:Tvlh1OTBs2ZQyzxsFSG94g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:TU4r50IOpBRvs3gD6jg=,iv:hb5uE9+FAd8gNr0rpzXVCHUITE2UTMw9AbZmNtztkoY=,tag:QmJjE68HeFkuTZ097jkKrw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:jUynvf6TLvPEMOMs3NJY89Di8CbiM77iHC7yQrQpA39oUilq,iv:yEyIsyilWvODrdDeZ+Wbw9Rv1oSnPyiEkCVU8ywzbx0=,tag:wTOd7J1ykney15CkiP8Geg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSklQK3JLWlVwUzNsbXVH
            eldSTzh4eU5kQlFUdzRNZG5obk5ha0FKTkd3CjVER3ROMHVjdWZsYk5TK2pnMHdN
            UFhlNGZENXk1Q2cwVGtHQUtjbWpUTGMKLS0tIEJTMXhNZ3ZETTBkcENzRVFaUlpp
            aE9zbWkzSW5iUVk5QjdhNGMxd0dtRk0Kxz1i87xaZew43uFptVHy/fBIs9T+muy0
            BpqQXggm2PYXNiwKlVEjQZUgRoVI3MR7OUUpZvRRLRrBtMwuUdrobA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-05T07:07:57Z"
    mac: ENC[AES256_GCM,data:/u7KlvcdfSMtHS9w7H680oAp6MDXvB2Vqcd0VNNN9A6rt8fPwHGpBRVs8/zvH5Y87m99tGtSOYipDW5gE/+ARc7ohE8DrgKnv4Yuxx5FFL2lSKYyvRtj0rwHx04DEIJeaXMs3QX0AV8NVW+ulGGWTkNQweH1FrzIGc+xsVOEyCw=,iv:jAtDhzf+hVbPF1EHOoy0O9p/neCHwCpQ7CIAprwUInQ=,tag:YyNqISrhtqluqCV4c+foqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
