# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard
type: Opaque
stringData:
    rook-ceph-dashboard-password: ENC[AES256_GCM,data:DL4QZ/jir1aPsov8,iv:Pnb2cTdacBSWrDTbTjhvUXSsH1ytJtoFBIB/EJwCBUI=,tag:oAHgwdgew9XoMjBK8nQU7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVmxYeGgrT05jei9ubG5s
            cUllRGp5MU4rQmc2SFA1bEppYVdqRTlxSlRFCnV4eUdydE8zTW4weUtqVFlFRGNm
            ZzdoWWdGa0QwWkJHOE5DV3hnSmxtSmMKLS0tIDNYcTdrcHh0emh4TVNpUFYwRmVu
            R1hXOUVRd0hGVVprNXdMckowcnRQMDgKPJoqk9JetF9590p1C4iIRFKSayKhepGg
            O7g8r47ib1EnTGY7fLhkB0JvGofoBA2Qorv3/TXwpLAM1dYFPjcnTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-09T01:27:46Z"
    mac: ENC[AES256_GCM,data:B6xdXKtTpZAt3d1DqS2m7w5oPoHIs7fds1ZO1jgx9BAsDquQLfUAmLUAyeRMudFNQe9/XeHg5wVqco7eSMP1xLgfEKGc5qPHah1SFG855AhvM+qtHiGw8h6xUNAqaCg2oxoGkvt1dMq1PHWPYZpK+9q2bpmedhQf/t14cEA6Z/U=,iv:LSBxtlb1I2P+gzncEn9i9tw/JTht5O8KrG2FIwjvpSU=,tag:1VlR4cN0gYsmeQdtmoMMOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
