apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secrets
type: Opaque
stringData:
    mosquitto_pwd: ENC[AES256_GCM,data:igjsvqJK/0w4qiLZg+jB59p/DOujbzGDUG6ciN7H8kOJX4OqFsQFQbmFPB7d4wAGZa+sDIi7mNapAsaWAaPdFB5YAu2fQMAwGPAnoLY=,iv:gu7ulQLRatpGyZUQCEiJ3CDPhwqtyzDQIAQYMRs4BHE=,tag:AOzJHmbAqch6fi8z7YMHrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVmxYeGgrT05jei9ubG5s
            cUllRGp5MU4rQmc2SFA1bEppYVdqRTlxSlRFCnV4eUdydE8zTW4weUtqVFlFRGNm
            ZzdoWWdGa0QwWkJHOE5DV3hnSmxtSmMKLS0tIDNYcTdrcHh0emh4TVNpUFYwRmVu
            R1hXOUVRd0hGVVprNXdMckowcnRQMDgKPJoqk9JetF9590p1C4iIRFKSayKhepGg
            O7g8r47ib1EnTGY7fLhkB0JvGofoBA2Qorv3/TXwpLAM1dYFPjcnTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-09T13:55:01Z"
    mac: ENC[AES256_GCM,data:44Ky+NoyiyjEVsDqUl3J7iNG+4zZwOSTU1aDhjU/Up+2eFvrrQWNIfuuEufYPdy8Rh+0sO+vF264i3dVIT0LsGN8HpGXzKaEnrlYtGbXaYLNjZ8+VeZKyuNiYnyxYZP8KArTDaH6awyGKXRrpH9f1V2NhNI7Pemu8t1DEVgslCo=,iv:9ikxHApn6qBxugUqldhsk6xWa5cR7wTaA+1zhNRgC4w=,tag:nQMC7rkPFy9kWzaaMC5+ZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
