apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    CF_API_EMAIL: ENC[AES256_GCM,data:V8tPRrIPhcvENXfKfFw=,iv:lLeWNAp23/2a4ajqBlOkfddBZ6872Xt52DIuO+Wa1ls=,tag:WFGS/SaAXs7nIla2bkrnYw==,type:str]
    CF_API_KEY: ENC[AES256_GCM,data:dUok0U2e+vPPjwcp+lNstLdgyGG95jRuy7BJfhGejK0bgHGsEw==,iv:xGNjVnx5ocbIHXZWjvo0TgMf/dPER7oQC5HkKaSU4ns=,tag:Vu5HZAZUOXmqGPo/n5FoAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMENlYTFXeWVrQjluK3ov
            Mk5qc0F6SWVUUlNsbEc3SzljcWhIbjhrOUdNCnIrRkpBUG03L3ZieC9URjlUaTZP
            K054Zyt3c0tEL1VPczhYNnBreHZhbEUKLS0tIFhGTHkwd3FnQkdDTE9aMW5tdzVO
            K1k3WW04c2NHN1NYb24zTGpJckkxb3cKYKs9M61YC4UJQLNa8NINTWCmuRAC7+Gi
            vsR5ClGn+l4aFkh3NppUq4yV5tI2nWfwZDukgjS+WEDjZjAL8OSupw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T15:49:13Z"
    mac: ENC[AES256_GCM,data:QDZRkGN2aUjzAIZ2vPKhCzMz4juBqdloPJ5syfaXxln4vd8wWCU3zSNy0kpe9DtDdBNb9WKk2uH1Cc+uyNMOeZhke5E7cymm3yUjnk8myiufF8ctvh/r6b9l1gGOj8suYukxkwpsNqHhh3AvrBiHFBFGDTcRMoaqLnFeaP/A0JE=,iv:THCzuFGMVEvGRMt+boW7mAL7M+G5ZbsqHMLpA8knqj0=,tag:qNQNsb1CB/hI9dHfjJKk2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
