# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:KACnLg==,iv:cWX0A0hQrK1ssn3lzdxtPSY8uQChH3LxOYGcG8sDrks=,tag:R4uvZGB+DlJydmYXX/hrWg==,type:str]
    password: ENC[AES256_GCM,data:BV51nlL1ap42XmzM,iv:1REb9+ONA/7p5ZSGkvmgmu4KbgLJI4HykYTJBviP/xE=,tag:9QI+ISJa77AgsdAHb3/uSQ==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:r+BAsA==,iv:7VJi/GrrKyaaMa5f3uvZ55f5d0qK59EcosQ+7rpDwvw=,tag:89IJSnhlNAdj4hJiq1CWng==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Z9/t52dnJzzoWJl/,iv:O/2leRAw+4qkkecNVH1yxR16HsaK7nWb6aLpI2t4Sk8=,tag:uPkK7DRzNLOH1kZn+rCe/w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:n3hwLw==,iv:xTYWkHblNcMBeU4foNb4P7G88hTHzQDPnJgEQVbK4Wg=,tag:+M9SlgCXyf7ADLMlRxkOxw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0q6aff0lfmnEzNGr,iv:hhx7s8EizVOYwG+1+nIaFPcTx8kXtoDCJz8duIk5+gY=,tag:t9C4qHcprdu80VId98FwFw==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:NLw5+7jKAkzmDVInHdkCOU9BOgM=,iv:iO47TPw3hhqPyGwUMlIq8ltyEQCIHQexo52UiO0m9dI=,tag:3E0aU+BLFIKIMgQ6lfUkdQ==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:A9mDuipsZVeUuf/N3ZtMwqIRcl5x6au8ExC9hr5zttkvQqr2NGgxSw==,iv:WtbvUNUaXtaXBbBESzh5XsbgVPZdwiVCkX9ZMU3t+18=,tag:xlqlYU47aka5BC1P8fh5Yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVmxYeGgrT05jei9ubG5s
            cUllRGp5MU4rQmc2SFA1bEppYVdqRTlxSlRFCnV4eUdydE8zTW4weUtqVFlFRGNm
            ZzdoWWdGa0QwWkJHOE5DV3hnSmxtSmMKLS0tIDNYcTdrcHh0emh4TVNpUFYwRmVu
            R1hXOUVRd0hGVVprNXdMckowcnRQMDgKPJoqk9JetF9590p1C4iIRFKSayKhepGg
            O7g8r47ib1EnTGY7fLhkB0JvGofoBA2Qorv3/TXwpLAM1dYFPjcnTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-06T10:04:18Z"
    mac: ENC[AES256_GCM,data:Yy/BsRiSq+wsbFiZa/xLXIKEhQKo4WLuBp+TFfsWEly1DtiB+OH7n2oUXbex8P+hk+CkDZsptApPYj9WJt8GfPVhgJKT4R9Ma3+756dURSXBv39pz/PSkjlOo0sZQIp4J7l/9rEXOKK+4oOu9GfxPoUJj2anb/Aa1UK1hKmjuFA=,iv:iGTmvcS5h56A0NtE6IA9PZlVJPZRvQdjKaB6eNrGDzQ=,tag:ZlHFNTBcQlKdaQ2i5I3bIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
