---
apiVersion: v1
kind: Service
metadata:
  name: &app postgres
  namespace: db
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.${SECRET_DOMAIN}
    coredns.io/hostname: postgres.${SECRET_DOMAIN}
    io.cilium/lb-ipam-ips: ${SVC_POSTGRES_IP}
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-v16
    role: primary
