---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nanomq
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      app:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: emqx/nanomq
              tag: 0.21.8
            resources:
              requests:
                memory: 128M
              limits:
                memory: 256M
            env:
              NANOMQ_HTTP_SERVER_ENABLE: true
              NANOMQ_HTTP_SERVER_USERNAME: 'testing'
              NANOMQ_HTTP_SERVER_PASSWORD: 'testing'

    service:
      app:
        controller: app
        ports:
          mqtt:
            port: 1883
          http:
            port: 8081

    ingress:
      app:
        className: "internal"
        hosts:
          - host: &host "nanomq.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: "mqtt.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: mqtt
        tls:
          - hosts: [*host]

    persistence:
      etc:
        enabled: true
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: '/etc'
            readOnly: false
      credentials:
        type: secret
        name: nanomq-secrets
        globalMounts:
          - path: /etc/nanomq_pwd.conf
            subPath: nanomq_pwd.conf
            readOnly: true
