apiVersion: v1
kind: Secret
metadata:
    name: nanomq-secrets
stringData:
    nanomq_pwd.conf: ENC[AES256_GCM,data:hMGubH6IHMpo5YGOnjpcXx40HdMfur5dmElP6Stvmz/xT8/x,iv:AgxtrNvRKZmVLZpg8Dxd04R9iKMg8PrFPO04APdRa4g=,tag:otC4V8ZGdKxO4j2o5WqnrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTjBmNmdlTkl1YU1TQllV
            RXlWU3BnMEFUbmUycDZxcVRBMWdoV3ExRDNvClk3Kys1WVlkb2M0S3JCeUpTSlh2
            dThMYXp3K0VIbGtvd0NRUUM4d1ZZN00KLS0tIGFYVC9NeHV0ZHlNSm1VNVBMWWJx
            Zm1zbjlXeVU4RExKSVY0VHlXUVZmWDQKWSjWAqIVYI8mJBgTsX1/EZI4NIAXPYyy
            PybmiHETrU+PA8GLWGT8EpsaIIDR0qwtNPbJtiKblIf89gW4Vw0k4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-07T12:43:34Z"
    mac: ENC[AES256_GCM,data:KNM3WpsEpaDvCW7Yd3MTJ9cAntJ1yqLk9mX1oi6ESF8926P6/uE5NI+pR0hUfhwPAWf2m+M4JIXftXtUO8h18wbs3gp32EUZD45TM2OmhCj9sXoSDTRpROIL0LNJVpcx7UymXXP7Bs45RGtD4GOIowNPKb/b7ESJBZv/k9Yb/fg=,iv:UYwm74wovxdeZaYRECtf7T+6N1Uzn6C2YlMBv+siB5k=,tag:P6YGYSXEariZ4rVOS+EPdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
