apiVersion: v1
kind: Secret
metadata:
    name: nanomq-secrets
stringData:
    nanomq_pwd.conf: ENC[AES256_GCM,data:hMGubH6IHMpo5YGOnjpcXx40HdMfur5dmElP6Stvmz/xT8/x,iv:AgxtrNvRKZmVLZpg8Dxd04R9iKMg8PrFPO04APdRa4g=,tag:otC4V8ZGdKxO4j2o5WqnrQ==,type:str]
    nanomq.conf: ENC[AES256_GCM,data:Odqxgwq4TkwQc/a5xI+Oc1bVvuLwcHuY24YPA1UXCtAtq6/a5Mmo/xHI2BN4P9OV5S/j1Fwecw+km+O8hJGWUhJJ/TZJNJlHwYRr7Ysi3T3cegc5ihimO0yF70uf1aFjCv0OHmW3w+2YWa+3jDKH4kl+x6z7L8ns9iiNNMzWFlChk7JYi5og2TgrE9JMZbp5EFJHjHhWmgnhLIXDmpqUYiVSCZDzkGejZ5Z9rFvpGJ32rL9HkZVz/FxaLrd/vbhklkG3Hsb+xLak7FwdGgqvuDc3Otq7AtrORYUhC/qfKOO23mHaf2daJbOmSd/SJgdMy2UOhlDZhPQ9bdXh+T/s8Pe+2jpNLGS+fcnjn7LNDHcOFLAKv0zWegX5+f45v+4ukjJKc+46DO5XFTPvvpaYGQxgHupVSkMa7DHz/3TGyUZWfJcEPzzDQOyVBOrJ/3iLLbiRpuWaaob5B6O8uEPkH4QSOwl86B1+vysFOBcLw9IW29+OexYNs3WVNbEWm+hrpvR8lAC+yfjztoC2RxgGdspAKbHhN+ZGF+BJu8JLUUVfLlV2LbVK8MYbjEWQLsuQSLQ5pNtfwByJ8HWSG/63xLrrF/K2ZKY2f6QwZAncdqzTEk+v/Jm0FmyGZkzG/T3uDuObd2F8xOjjPShMCKD2SbphkTcU5VPgmgZy6P0X7EpsiAFbcX9aM+5vBXmAysyG6oLlODUf4Zi4zkD3q/tK5R5YfhvlMlMFo5rebt3BDw9yopwdn34awXDgk3L/EEDfma+t3kXBUDCOTlDqfZxxd6p8ce+Pjmww41PBHLSLMug1jdxrdfhB4zCtjBOau+9cRhSG/5YonwF/HApH1xH4yAOI/FswpA0xZRBBw6FN8H6JIBDxMFQl86MyRPat2CkyJCszk5XaprfcfnU8/Rr8Fi/vA5HJbhz16JqPoWGfDERp4vQ3q+/4OqeW0hzc+QiZsHPaoXd4ow5Xz4xvCZFe0IaVh0vE309XO503mxyUoqzh2erVwv7Teo2Q3YUXwaLqQEBtMVkoT3bj1c/UkQ6b2aWKl4FqrYazkhDW7bdHvLEf6pXXneYrf8RF3ehynGDJRuySrS6YWp1wppnvzj83N4pO0XpQ6VyzGqzOCv6E8gQjH1gVB1jXHkGjdem8KFdRifj4UUSnz4XpdB42O5t0iixwuWa6N3PX+Mt+EiuwSBXsTC5PRW4ypAS2tpkEuf2AstOAJtAr71yDevY8NzM8YZNhxtDrDQB59yulnIdm8Fcs0A6r2P79jzt0fuy4Xbbx2WPP9r6VyiXmkJk3G/WZNTpiH5M61kuMX6/7QSex4C8=,iv:MYh+6H31Blkasd/duCy35zi6hBq6FXFVhZLmWNRkBhE=,tag:Ureu4YTRDL6EgodzT4aASg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTjBmNmdlTkl1YU1TQllV
            RXlWU3BnMEFUbmUycDZxcVRBMWdoV3ExRDNvClk3Kys1WVlkb2M0S3JCeUpTSlh2
            dThMYXp3K0VIbGtvd0NRUUM4d1ZZN00KLS0tIGFYVC9NeHV0ZHlNSm1VNVBMWWJx
            Zm1zbjlXeVU4RExKSVY0VHlXUVZmWDQKWSjWAqIVYI8mJBgTsX1/EZI4NIAXPYyy
            PybmiHETrU+PA8GLWGT8EpsaIIDR0qwtNPbJtiKblIf89gW4Vw0k4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-07T12:49:15Z"
    mac: ENC[AES256_GCM,data:3eBMLnJIuLRh47yQnvHLXXieXlmJ60aPR1d5vyKxjF4pqGA+AWH+LSbOH4S31/7z8X/aTZ4xzE1JgA5+jVYsreTGToRR2llugTl5Xjiz3pdER/1iTAutJeSQbEnpl01hRcBwdVHvfHplRvxaEtR0HD+8IuU4UTsSm0hHgsWepOE=,iv:cmYqN6PAccEWDSk/Vmn4INMGGqLBEgc5bKZ4iK4kxMk=,tag:hOf4OeUM+ftvTIrz9zrX4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
