---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app hass
  namespace: flux-system
spec:
  targetNamespace: home
  path: ./apps/home/home-assistant/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: openebs
      namespace: fs
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: *app
      namespace: home
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 3m
