---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      cloudflared:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
          configmap.reloader.stakater.com/reload: &config cloudflared-config
          secret.reloader.stakater.com/reload: &secret cloudflared-secrets
        containers:
          app:
            image:
              repository: docker.io/cloudflare/cloudflared
              tag: 2024.9.1
            env:
              NO_AUTOUPDATE: true
              TUNNEL_CRED_FILE: &credentials-path /etc/cloudflared/credentials.json
              TUNNEL_METRICS: 0.0.0.0:8080
              TUNNEL_ORIGIN_ENABLE_HTTP2: true
              TUNNEL_TRANSPORT_PROTOCOL: quic
              TUNNEL_POST_QUANTUM: true
              TUNNEL_ID:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: CF_TUNNEL_ID
              TUNNEL_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: CF_TUNNEL_TOKEN
            args:
              - tunnel
              - --config
              - &config-path /etc/cloudflared/config.yaml
              - --metrics
              - 0.0.0.0:9090
              - run
              - "$(TUNNEL_ID)"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ready
                    port: &port 9090
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
    service:
      app:
        controller: cloudflared
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: cloudflared
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      config:
        type: configMap
        name: *config
        globalMounts:
          - path: *config-path
            subPath: config.yaml
            readOnly: true
      credentials:
        type: secret
        name: *secret
        globalMounts:
          - path: *credentials-path
            subPath: credentials.json
            readOnly: true
