---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dnsendpoint.yaml
  #- ./secret.sops.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: cloudflared-configmap
    files:
      - ./configs/config.yaml
  - name: cloudflared-credentials
    files:
      - ./configs/credentials.yaml
generatorOptions:
  disableNameSuffixHash: true
