---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secrets.yaml
  - ./dns-endpoint.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: cloudflared-config
    files:
      - config.yaml=./resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
