---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-secrets
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CF_TUNNEL_ID: "{{ .id }}"
        CF_TUNNEL_TOKEN: "{{ .token }}"
        credentials.json: |-
          {{ .credentials }}
  refreshInterval: 15m
  data:
    - secretKey: credentials
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: ${TUNNEL_SECRETS}
    - secretKey: id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ${TUNNEL_SECRETS}
        property: id
    - secretKey: token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ${TUNNEL_SECRETS}
        property: token
