---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: "d6d3ddd0-0e51-4cf7-96c3-8c52ff415ed5"
  TUNNEL_TOKEN: "eyJhIjoiNzE5OGM2OTdhNDZhZGYwMDJhYWQzMWUzMTU2YTYxMmIiLCJ0IjoiZDZkM2RkZDAtMGU1MS00Y2Y3LTk2YzMtOGM1MmZmNDE1ZWQ1IiwicyI6Ik56Y3habVE0WVRndE0ySTJNQzAwWTJKbUxXSTJZekF0TW1ReE5HUTVObU0xWkdWaSJ9"
  credentials.json: |
    {
      "AccountTag": "",
      "TunnelSecret": "",
      "TunnelID": "d6d3ddd0-0e51-4cf7-96c3-8c52ff415ed5"
    }
