---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: "81a81f1a-430b-4ebe-b374-ab1e034dc5f5"
  TUNNEL_TOKEN: "eyJhIjoiNzE5OGM2OTdhNDZhZGYwMDJhYWQzMWUzMTU2YTYxMmIiLCJzIjoiRlloRHhZQXVJTTRqd2JQa2pZVXFKazAzanJ3cG0xb293SUFMRi9ETnJOYz0iLCJ0IjoiODFhODFmMWEtNDMwYi00ZWJlLWIzNzQtYWIxZTAzNGRjNWY1In0="
  credentials.json: |
    {
      "AccountTag": "7198c697a46adf002aad31e3156a612b",
      "TunnelSecret": "FYhDxYAuIM4jwbPkjYUqJk03jrwpm1oowIALF/DNrNc=",
      "TunnelID": "81a81f1a-430b-4ebe-b374-ab1e034dc5f5"
    }
