---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./claim.yaml
  - ./secrets.sops.yaml
  - ./helmr-elease.yaml
configMapGenerator:
  - name: mosquitto-configmap
    files:
      - mosquitto.conf=./resources/mosquitto.conf
generatorOptions:
  disableNameSuffixHash: true
