---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: olympus
  DEPLOY: live
  GIT_BRANCH: main
  TIMEZONE: "Etc/UTC"
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "10.0.0.0/24"
  GATEWAY_VIP: "10.0.0.101"
  INGRESS_INTERNAL_VIP: "10.0.0.102"
  INGRESS_EXTERNAL_VIP: "10.0.0.103"
