apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CF_TUNNEL_ID: ENC[AES256_GCM,data:B/4LNDTKyW68CLwHYbtmgCBHoj9l9sc0azi0uYrswYH9b0tW,iv:bKPBLrZIcws4ZOgAwWZaSxZcI70FFeOhksCJJ6DrEBM=,tag:HOOupcJRlIxwqb30mPd3Dw==,type:str]
    SECRET_EXAMPLE: ENC[AES256_GCM,data:zeo72uzRnXfawzI9pcifKbZLijpAQUCzQacWO3KoKFS5GW2IS93YGaVEiM89XMrsCMqYlnRticHJif3l3n8WOFC0LKU4ZiMnYm/Mkf2m1HGvcXk7J0/pWSaFTOVuhg==,iv:Z+u07xu9BxIhISD2YCyTVypHo/MhK6c7iR0PqfPqKZI=,tag:RisD4JzAmRBiQycHYU9f6A==,type:str]
    SECRET_CERT: ENC[AES256_GCM,data:UqL78BclDm+YPA==,iv:QVr0gfO6jXNKYgMT91dZvko/rQ7dxqZAKKXgk5zD9e4=,tag:3krQk0zkODvbz7kj194GLQ==,type:str]
    SECRET_TLD: ENC[AES256_GCM,data:FTQ5GI6bXsxhZsI=,iv:XE+zHlr3Rrb+B4NlSK1fbQ61HQBuU3nCc/2Q1+3tcjE=,tag:PRWwWpma5wCO39yjDfz7gg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:fZZqwDzAXa1nP9k=,iv:KgZxsNXCtqgnKWPK1ekqDEPAtLItKlH24voFKezJqaE=,tag:0J1nrCV/KqR9QxK2Qjdr6A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:eHrtw6jTOKu8C8VtvPg=,iv:b5OOFM/XLYzgb96ErAFhKh+D+BcqxMWdp/gCAibDEsA=,tag:hsIUrNti2JAuQK7t0swkfA==,type:str]
    DOMAIN_SUFFIX: ENC[AES256_GCM,data:uXx0dPHg6mgD99AT,iv:aevqSXi/hPPQ/aVnvLXPqej96E3iZIsPj1T6pOds4C4=,tag:RhTeC1+7Quwf8hhh3J/sNg==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:yghmtJ1U8wN22HvImrk=,iv:CpVJU9uDVRCI21viAuWfezq1YGFQJVbFNCWlkldc0rk=,tag:uCvqc366zIsW26rgC/W45g==,type:str]
    BW_CLIENTID: ENC[AES256_GCM,data:AhGYqv46VJbsUGg1VgfHYGkHsXra3yn3o8Q4CJIdggMiFIERVJgMvgM=,iv:hONB5qzMItj0KXBlm0aqrC0ARifEg/iC6msk8i4hneY=,tag:TMxJuxJ76nEXQ75uHSkmxQ==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:Fbt93w+w1AOptQO6z0prn+5d720D10J/j2VqBtr/,iv:olnRJ1AjPJ0LNecxFNGyWIbzSeWosZcx2I7sB3EMd5c=,tag:6Ql4u+cwVqwKGiiRiRdaSQ==,type:str]
    BW_HOST: ENC[AES256_GCM,data:/HSlkoEqMwEK6SyZNg==,iv:DgbVrUUTIIdgIvEwpmW2oDTdTYMZXOq43EfyldkCGOU=,tag:RNGyeY4n7g0l1aEkJmMajg==,type:str]
    TUNNEL_SECRETS: ENC[AES256_GCM,data:vdm9mswLZWNbxwnp2SXqSio1VQRG0GM2Hm//M1erqa//NFSm,iv:vdrb2HA2GwQGiTS2ilIXlgVI2bTp+qJUbkcxw+SdH7U=,tag:1reVezs3+5/n67LDPdDasQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVDZQYTlzZ2U5czNUU1Fi
            cHVhM05YcWZhOGdraDFFU002TGtLVTF0N1RBCnkxRlNVNkZycUZmbkpHOW5XQnJC
            dFQxRkc0dWZaeFNESmEyK3g3QjVjbFkKLS0tIDNZaGlCQWd1RUIvc3RWeFZhcGRr
            bzRPWlJrNnhuYXJQK2t2WHNzWVRrdVkKaLWFjpnxacZEshnGhOZg/4hElSt4EUhC
            wQVsGes+HtgplrOYo1uOhjXxXantConuaMeSHzafpnm3XAKF3BQ63A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T07:40:09Z"
    mac: ENC[AES256_GCM,data:3ZYBO7Rakb1l7n0VQXK2+4VDpLszAzwBWuqlfpbNJ2CFttJipslXmFkum/WZXGMmDSpVAgy8va0IftFPuELcpNOMP/J6LOA7jX+4ko0O2tR6GPE64VrPXvpZxFr3IA7JYhgcyeLtvVAffkVkqMHh2Qn1LOhsoFGZCz+7oEfYXW4=,iv:OtbtGxbiK6Yc4Ba69Uj1f5hff1WI8oK1ltp1GW7QZLw=,tag:3oteDn08YO0T3tHyBgxk6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
