---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_EXAMPLE: Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...
  SECRET_DOMAIN: "itstoni.com"
  SECRET_ACME_EMAIL: "me@itstoni.com"
  SECRET_CLOUDFLARE_TUNNEL_ID: "81a81f1a-430b-4ebe-b374-ab1e034dc5f5"
