apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:TJHymlJUfDDCx4aYbqH2iYeFZjiJ08Oe+DGS7JbiX1qUaiqRVj56cg==,iv:TQMdN8Lc30YDfUA+gJsjh8436tGRvDQqMT2bDx58UhY=,tag:lvUCvJ5iQBd1QnRPl8vPNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMENlYTFXeWVrQjluK3ov
            Mk5qc0F6SWVUUlNsbEc3SzljcWhIbjhrOUdNCnIrRkpBUG03L3ZieC9URjlUaTZP
            K054Zyt3c0tEL1VPczhYNnBreHZhbEUKLS0tIFhGTHkwd3FnQkdDTE9aMW5tdzVO
            K1k3WW04c2NHN1NYb24zTGpJckkxb3cKYKs9M61YC4UJQLNa8NINTWCmuRAC7+Gi
            vsR5ClGn+l4aFkh3NppUq4yV5tI2nWfwZDukgjS+WEDjZjAL8OSupw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-05T07:12:11Z"
    mac: ENC[AES256_GCM,data:5PgXhTxOSV25mbAGZcO2df1g/wg+Z1d6VmJAJhdkBas/BfkBdh2sT1/MjB2MHQvB6hDXfmRUZP/nxm2HDyV8hMioBc0abki/pCnrGY6w52nOLqnGfCEluC159XFjbOZAsabr8Qrgij26lEGSg9DTKI9xW0GkTlvlmJi1MPHjFiA=,iv:HA3r/QkcFkP07ojm5rJgQOt4tgek2Rmw7zDLDKcavx0=,tag:GC1hEmFkWMQs7AS4QiXpXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
