apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:nKwLUiHVMcuZWqKh4AuQTkhgjvWvE+oMN/SopvuvhUkXyw34,iv:8zC1B/VYgwqiKlmiCCxEEkK/vUdOg68LachE8cK+xfc=,tag:41KR+iR+qGGZpZO3PAOc9w==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:YtioJf7RWwepBGRJ/czl1i5px1eRSe3aGSR8pAIeaHkJcofp7cvOCvhYQxKGfHMFcIHlnzlxA+AmfYFc7/lHEqcBd0i9DqENzwvm0b6CzxflOEgXshJLV7qJP+b8gxmGfdkVKAe54Bpx6WMmSYxH9VBoDAZjfGTmEERSVRuuFNE1FD2lBh0O/Yq+oH5jDAcBjgxfjLAsdQsVTAvB+S+fKdp3Mg3EWhWo4WqHiSXAdkdXxOI+,iv:A6DTkHbgyCE4mwOCYXL+j4l9odwn/TNpbMyMQteWiRI=,tag:XUb0R9d3pTFvY/87Vf8qzw==,type:str]
    credentials.json: ENC[AES256_GCM,data:CqA4eFa4iLOrvy3z/ST67AYe6dMatODuf7FlDBiEA6ACMr7wwjqSGFdF8G/O3GROGttigJWCTDYSpq4fgH+QsjSE8MZLeHDW1L7LI3iw5RYrWx3pIDXc9IAxo/A2mhZy14ngG/t1hP/ByJn1bOSDRqHwyVqHNDnw6Jl7KtcB5Ke0HwkvS2kfyA5A2EfbzIPRbPHz3nz0+v9JCw/HdkaA1AilY9NhHSzbGJ4xgOrfnA==,iv:OmUtps+oQvb9dDj22Ek5Q+qLn+HRP9IJ8VzrXos7c8c=,tag:LMW4Q6CXAXRTlnqTGe+pSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL3I1MlI5R3V2VEdLWStH
            Si9SdDJoZm4ya0Nha0d6eUNUSjkvN2lMN1FZCjRVMUxUVFZyNVFNcURlZGljWUcv
            aVMwamxwd25lSncrbk5yU0pCaVdjL3MKLS0tIFJJSlk1Vm5HVHFITXYxQmJvV2w4
            bnBKV3BxTVpWV2RkdlVtd0dnSTYxRGsKupnNQfHHm+lLbPJWdsE6drqQ8acbLJwF
            m/tYGZXr6S4khW1eWUdmBzU9UZnLV+J9zm52N8CCLn2hkt2dOijHSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-05T07:07:57Z"
    mac: ENC[AES256_GCM,data:yXGmllbP/vzduuuKuklIkLSMO4V8r8sPSSJsmld2EHyzTG2gSYRVEciAotesBOVHjNxkhwok05GKBDxjDE4qU9UbTYg5wsDiJVc4DmywizUxUjjgB8ngVbEpcBe9+pNY1adXL8uFcmY7dUonmCUQLU3RokPiiDhQqiOYBGar0RM=,iv:Ms9jEoP0WYJKeoE9lwtrIQfCyaI3d6xbdwNCJ0hgr0o=,tag:ENwToTURlDNCgoWqRIS8Ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
