---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 5Gi
