---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MINIO_ROOT_USER: "{{ .username }}"
        MINIO_ROOT_PASSWORD: "{{ .password }}"
  refreshInterval: 15m
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7666f1f0-9412-42c7-9f5f-b1bc00593d28
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7666f1f0-9412-42c7-9f5f-b1bc00593d28
        property: password
