---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app purus
  namespace: flux-system
spec:
  targetNamespace: home
  path: ./apps/home/purus/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: openebs
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 3m
