---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  KUBECONFORM_SCRIPT: "{{.SCRIPTS_DIR}}/kubeconform.sh"

tasks:
  resources:
    desc: Gather common resources in your cluster, useful when asking for support
    cmds:
      - for: { var: resource }
        cmd: kubectl get {{.ITEM}} {{.CLI_ARGS | default "-A"}}
    vars:
      resource: >-
        nodes
        gitrepositories
        kustomizations
        helmrepositories
        helmreleases
        certificates
        certificaterequests
        ingresses
        pods

  kubeconform:
    desc: Validate Kubernetes manifests with kubeconform
    cmd: bash {{.KUBECONFORM_SCRIPT}} {{.KUBERNETES_DIR}}
    preconditions:
      - {
          msg: "Missing kubeconform script",
          sh: "test -f {{.KUBECONFORM_SCRIPT}}",
        }

  .reset:
    internal: true
    cmd: rm -rf {{.KUBERNETES_DIR}}

  cleanup:
    desc: Cleanup unworking pods
    cmds:
      - kubectl get pod -A | grep Evicted | awk '{print $2 " --namespace=" $1}' | xargs -n 2 kubectl delete pod || true
      - kubectl delete pod --all-namespaces --field-selector="status.phase!=Succeeded,status.phase!=Running"
      - kubectl delete pod --all-namespaces --field-selector=status.phase==Succeeded

  secret:
    desc: View secret
    cmds:
      - kubectl get secrets {{.name}} --template={{.prefix}}.data.{{.key}}{{.suffix}}

  node-label:
    desc: Add a label to node
    cmds:
      - kubectl label nodes {{.node}} {{.label}}

  node-rm-label:
    desc: Remove label from node
    cmds:
      - kubectl label nodes {{.node}} {{.label}}-

  context:
    desc: Change namespace context
    cmds:
      - kubectl config set-context --current --namespace={{.ns}}
