apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:HmHqnSgs5+ZTtARkwPaWyb/uwxSQf44ttOyETfCCn30+GMJenpiuLw==,iv:FmHr4g5N0YhzjHLJXWGEPtvRHWZU0VvRAboZS8Yzvf0=,tag:pMYOJd3UsCzbC3qyorHFLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMzg4aUtVMWphTGFCR3p0
            bnZsVjBCSlVnbWgvcVc0WmV5cWhETlJHSkc0Ck5GS2NYVm5GNlFuQ05DZjNjMklj
            OHdiVTBkd1BQa1BPeVhrMGIwZC9QRTAKLS0tIG5ZQm5MVlVaYkcrUGdjSVJrd0Ra
            N1lMc251a1gxUG5TUk0xTlZZSlpaUmcKn7k6+3a/FwQVEIuQT76Us6MscZLyGraw
            CLcO3OpZoHT0wlrJ8YwzzTg5TNHuDRtrVZDxldQNFgdfcKm+o3XLew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-04T04:40:14Z"
    mac: ENC[AES256_GCM,data:4PN8ztAgNojEsdAAUU1+/uC1NdfWe3kmSER7jL+FayZv5T8RctDdA7seqmNSEEzNiJRHsQvnw0giF1Jnx/DyUjsNogaQw4w4IWgQ0tn6ro0t5GcBlAFL7klM0wUhEPfrJ/rMyAb/aEo6HEnU0l0qW2KXtrdWpPhivnZuE7EZx4A=,iv:j84z9Tt4xljhG0ZMpJ1kWdt+aZPLqEASyj4rVovWUiw=,tag:M1HQymAQGyMRpoL3ue4Rsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
