apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:mOZ76nvmtszFoJduEyIlwD4tpUemRVJbGGabrFL415i0qWiAjoxbZmE99QvSLUzah+abebKrqI2J9E8+IMiRA17vqUg2YNhCI3MYRLALfyhBZu3A+SqkKxRPi6TTBQ==,iv:NsY9QNAG+Wc3Nd6spjy6teFnMmXualITathe/qQPNGI=,tag:DX0l3GNF22cRxys0P09RZw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:CJfc/1GNwq284NI=,iv:NHIGJ73y2CpsR7Qx1I3HfN760QWV4nmw4/ROevCCygM=,tag:AFJ/1YRpOYxzN3eWvplNtw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:4f+ZS2lsqJjpwrtARHc=,iv:PL4KFSnoXoXlH5KWDLvJoz2bsofMdSORXymMdht68hU=,tag:63nV7TkUxljj4/iwI4UJPQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:sJ8fwfvrCWFzj/okPJiyMDVfiaEhqXlDh1uNFIrbj3T+LBb8,iv:kfmb3YXXd5/8cWcwEf5XcbHgZnv7ctacH9OxOYFkJrI=,tag:IuvhMz8vNwe99720ADlYcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZlAxekRsRjFtMmtpVS9y
            blFvVHAxd3V1RDV4M1R4OHczZURhZ25idDBVCnJ4UHF2UWNqTWJlY0JPNjlMRktk
            aWRzaEQwYVYwa0t5OTNHUkFBREIyRlkKLS0tIHEzQ3ZaUGFQYW1RQ2JYNEQ0VUpI
            RWF0ZXhOYXVhclBSYXRCZWJ1V3JNZ0EKzn8OI0dkI+SPmLzxWitFwF5NziQAXS3K
            NFfDNzDsErTEPybcgLoHsCw2rxS6VZjwCaQ9P1t/iRMdy8mn3e9rdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-04T05:34:31Z"
    mac: ENC[AES256_GCM,data:H/yhTxAkmVeS3n8Xs27/CVm+N3g15taanybYr5b7uqP9NcDx5ZDunopYWYLVWpLgUjZAJ67xFo34qtnocVYuy+vVUXvWslgEfyp215EgeG2aRYQRdj8luvhZsdh9NGJYROG3GNJum6yfMEH1JaUF9fNZLZo0rWh0XtCe6pNJxSU=,iv:C3j/mP4MlS4Q9U3tP1Oz7rcRMYWYbT1clNYDjSvjSgo=,tag:S2BUmfRGK6IaE1e4/Z6lIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
