apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:4W9W3EMjulPZhPdoKPuZww3UNwX6D2XiHOvVa6Ne79Mfko2tT/8Rhg==,iv:8/Xp3jLTdQJDz5RazSEvtDVhmPB1d7om9K1iDwp06kU=,tag:AJpfn4jJx2LkOv5iDNztjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3c3pGZmJlanpTaW4zRDMz
            RExGZlZSS3UrRHl0dkNUUEQ2OEFFdEF5SVQ0Ckp0QkoyOFd6UUJ2di9QMmpOWThm
            dXVFdGh3dkdncWxwTDBDdXZJdWJMalUKLS0tIFUwVnFkd09yVVlPK3RJd2tiY1ZB
            UzZwVGgybmdOaEdYYldpK3ZSajNLeVEKSX8jAitTlPx6V/OTSf45+AMmA8KuJzpm
            5yeNH7wTGU8NNHZ/h35F9Lf6X5LyRTaLM6UFoRpKWYYj85KxfjG2Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-04T05:28:35Z"
    mac: ENC[AES256_GCM,data:aUEBnMRp1VPrj+G6OzXsTqnAXXovH09i/yj7mcvydvPJSkncnAXjynEi2zYXdR0yWfruQlm5NNRhno+UgCoB+mrckLI0aO92VkBiii0CWRDL8oCfYJGfhjoNqMAdA41nN5BBZUUY7cBzyh2u9ui4vXqDuAgXvp7gXY+B4NMagZ4=,iv:JTbe2nMPQu2lFH1EFtERLuf9mQ4rKAVcmToRUYwhu9k=,tag:wttuAUutW+76jaABWe9p1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
