apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:IKdBJleauLbYWVP27M7y3xxbpynO1PqFJ6BmowaHjvQwY6m1582DBa08bT3FP6JNtqqtRmIn9RKFOtVSPNNBhLh8t+kIehJVU6z6LxxXENQTwhOgz6oLsvPvpS/M/g==,iv:wLXR3V2rriC6WGXrY6TfzgQa2mvt/0oruEUuD3mzpAg=,tag:IL8go+vlCeZVLGFXsVrNGg==,type:str]
    SECRET_CERT: ENC[AES256_GCM,data:j8XMgkvSZQ==,iv:ufasHFVnE5raZrfMtvTxmlu8mNqNeq4j1tseziDev4s=,tag:EbwKBrj7zBugAsmZZEV8Vw==,type:str]
    SECRET_TLD: ENC[AES256_GCM,data:K6kgbxdSwDnqB8c=,iv:Y3/H/i7mYbegiwYrRoi4TyeSAs03TxOqOEXguKtKR6o=,tag:7kN+C2PpkLia/8nGO971nw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:VfPvIpeOhVcZLjHtBQ35/iElKw==,iv:jjfn/0MbMfYonEN+ahQChVDOEOt2Y9tyrjhy1pPVl60=,tag:Srpr6AW3L0gDt36dPAY5lA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:eCxpZCxWKTeuMeQkSGo=,iv:4MAUxAM8OS6ZixIj3Js3FC8CkGXAlGOQKFSNQaDWY38=,tag:QJW9flXhghFj98Tw9+dn4g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:FrdbZIFIR8i4IzG7qj7LMulwOJPTzRdiyziG4UFQj0SMGvcY,iv:sL1zeDtCxR8cgue09zO96iR6IpyktQbCOluu1BGPep8=,tag:MqVx0n7uU/4eZ3d9BFjSeg==,type:str]
    NFS_IP: ENC[AES256_GCM,data:OxZNej0dmKg6,iv:fH/OBw0uqsOwqWzAwoO9ZWOguv6DwG6Ltxc7c2iVP/Q=,tag:zDDF6Jsyk8sRzKWthYt2kw==,type:str]
    NFS_SERVER_PATH: ENC[AES256_GCM,data:wIhCkUGTk/cR,iv:WS1TA96jKl0DvEotInVsgHxD46lkC5ELxXygzYXdlRE=,tag:DF9AOFjnsqAb9EeSzN5hEg==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:Z6q4y+kn,iv:j3jgL+QPMivTY3R6lIlcFppuU3Wtw/6Iv7VnfDwFufQ=,tag:fAs2xD4rnMytKO+pSVjC/Q==,type:str]
    S3_HOST: ENC[AES256_GCM,data:9gVW+SkXhI1NSWxMXT0=,iv:nfO/w984p/NkH318ZYUZm4OQtDeXMpJpnJtNeRbRaLg=,tag:nXO5UASS+zDQdqccxn9Fuw==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:PIIb6pKQ1oFVeo/J3xVlX8SEK9M=,iv:GOLWY1NWCtrd5JLCKEb+lSgN9h9BKUe5Y694BaH+nG4=,tag:cUZMgruPjxZsgpI7RenL8A==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:HJXWCn28fU+Pp+vWx4xQqbpZYDuZN0nGb9envZMWdaoRm2QPjgHLYw==,iv:zAdURppk0TguDwSg3SXv6FYAYx8eASO1ybQnUVqnSxM=,tag:LtLVL1gxAgFRRj1ndGUDmA==,type:str]
    CF_TUNNEL_ID: ENC[AES256_GCM,data:hDxOkKJDjkELB/faA9bnWsStFllyYSw+MNcFElsEkPsue1Uj,iv:lR1lwEb1XYJnJyfv6h1NVsRv/3dVcnoq+u/k++KWTSw=,tag:hX0u7Dnfs7zwzk7brODlNQ==,type:str]
    CF_ACCOUNT_ID: ENC[AES256_GCM,data:jX4Cxxxk0hVqztSVHDMxnN9AA9jX+Zy6JLa4iVuMipA=,iv:VjHU0O07Yu3UNxevG1h3cQQ5pA5WuBds3fQ+FQnYHEQ=,tag:4rZwtoKG6QxgkGnSiHmQQg==,type:str]
    CF_TUNNEL_SECRET: ENC[AES256_GCM,data:HlmCqXInn1bu1oxozJJ4HRknxWyp1xKPuOIwaLLHe+1WRXurkD+9y47CCN0=,iv:JZcIgSbShvXy3mYpvsuu+13efIKpgRGcLQS9oWdrGiY=,tag:xp9E8oXEfHAWjMzmlVWZkw==,type:str]
    CF_TUNNEL_TOKEN: ENC[AES256_GCM,data:DwwbSBlGDweyEGx+JfhfT2c0G7WBPHR+2KuTSD6k11Wf6rSvMNAh2O7X3y66mXH6046pEpl2+Dl4L9uzHu9lYcj9h0BBUpxCD5dT7UBTlF5ROkDl7sP3BxIGTqKKuFv3eJF7d5dYr4tkPPHfal+4wfssMJppqb114bZbPS2PByDfGY5IY9fgvB4gOtVmM5Y44ZoKlNWXSfNQ1b/DT3G1zrIvTY3wWFhiOEp0CW2pBrb48Wwr,iv:WqFYxsKklYfF1ArJPilVgwPm0jMivqUubRg8iXi1jNQ=,tag:1azQTjonQ2X0d/vBK1MUng==,type:str]
    CF_CREDENTIALS: ENC[AES256_GCM,data:SOWZLrbLcbUGY45hywAzOTMoIssxIWToxt/nPt06D0nUd6kItuldNyPOqyZNOkKOHgqdWLhEewaADOZwUtmRy8EQsBxvAwSURFGkUfdPmaFeKcRH2+Cb3FfqeVSiQa8J+mGWdJcniwZ08as7H3zSYT3AgcxDvnw2upFzAGHkSRyvsuvCN+OiGtAKc15zMdDLzKXMYRh89ZLvqX1d08J7PiYCR7A3Vra60P4O4/C44Q==,iv:BCZf+ie90Z1fUwiU/HdDd3SInS2HwkZxYMPmEX/3Ozw=,tag:Ybh9g1MSpQ3M8v04kIFxUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j9n9mq2enuf92rrhnhxacgwv7kd8d4sf94eae9l6thc77e4ktu6swq52cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZlN5bTcwYVVXbndicExv
            M3FNVU9XKzVGb1g3by9WV2YzUERCdjI3MTBzCks2MGhiVEZNOGhsWVNvNWRsRkdU
            QW8yZC9ZSk5tOXU2RUFSV25xOFMzaXcKLS0tIEs5WGVKeEdVdEg1aUFuTEFTejVp
            cGhhZXdHSk4vaEkxejROOVIzWU0wNzQKP878UpRkt154BvzR81DjC2qcKZW4FTNY
            G7Y/XaILHCjUhOUv2lK7W6XctQ2gMeCmLPxZtJVtZtbXjx62oWRtfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-07T05:23:17Z"
    mac: ENC[AES256_GCM,data:ErHru9ucsp94GpCAf68qMRAKEGr1YYexRc0oxGSegwj1Gi9xowEYZTNvDVpILZCBC+7miTt10BZGYkKOLBlViOlHhuO68RQMNZtL9axPjhAuXc6Xb5hLyQW5XEEqEPKWC5EvTbOTCR28fL0IbjUokLlEAyMeUMXRwKQkuidUaCw=,iv:EEW/h+g9dOEFtA7QUTRua7vKwSeFa05XgT7QWBIzvCo=,tag:NN3hstJugDUPDx3GwmPjLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
