---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app nfs-provisioner
spec:
  interval: 15m
  chart:
    spec:
      chart: nfs-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    nameOverride: *app
    image:
      repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
    nfs:
      server: ${NFS_IP}
      path: ${NFS_SERVER_PATH}
    storageClass:
      provisionerName: nfs-provisioner
      create: false
